# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileHandler', '0002_remove_filehandler_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehandler',
            name='unique_url',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
