# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileHandler', '0004_remove_filehandler_unique_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to=b'/home/alexrazinkov/Projects/Python/Labs/Lab5/FileHandler/templates/FileHandler/Advertising')),
            ],
        ),
        migrations.AlterField(
            model_name='filehandler',
            name='file_to_store',
            field=models.FileField(upload_to=''),
        ),
        migrations.AddField(
            model_name='filehandler',
            name='bound_advert',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FileHandler.Advertisement'),
        ),
    ]
