# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileHandler', '0005_auto_20170104_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehandler',
            name='bound_advert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FileHandler.Advertisement'),
        ),
        migrations.AlterField(
            model_name='filehandler',
            name='file_to_store',
            field=models.FileField(upload_to=b'/home/alexrazinkov/Projects/Python/Labs/Lab5/files'),
        ),
    ]
