# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileHandler', '0007_advertisement_exposition_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='content',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='content_file_path',
            field=models.CharField(default=b'/home/alexrazinkov/Projects/Python/Labs/Lab5/FileHandler/templates/FileHandler/Advertising', max_length=260),
        ),
    ]
