# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileHandler', '0008_auto_20170109_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='content_file_path',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='content_file',
            field=models.CharField(default='cat_advert.html', max_length=260),
        ),
    ]
